development:
  adapter: mysql2
  encoding: utf8
  database: ligascfc_dev
  pool: 5
  username: root
  password: malisca1
  reaping_frequency: 0
test:
  adapter: mysql2
  encoding: utf8
  database: ligascfc_test
  pool: 5
  username: root
  password: malisca1
  reaping_frequency: 0
production:
  adapter: mysql2
  encoding: utf8
  database: ligascfc_produt
  pool: 5
  username: root
  password: malisca1
  reaping_frequency: 0
